### PR TITLE
AppRole AuthenticationStrategies

### PR DESCRIPTION
**Pull request by jimymodi**
Introduces Approle auth support.

### CODE REVIEW

**Comment by CSharpRU** [comment]
Hello! Good addition, but could you be nice and write test for it? :)

**Comment by jimymodi** [comment]
I would like to write the test. Can you help with setting up VCR and some initialisation.

**Comment by CSharpRU** [comment]
Okay, I'll write the test and provide fixtures for Vault, but it would be better to use mock of Vault instead of real one :)

**Comment by CSharpRU** [comment]
https://github.com/CSharpRU/vault-php/issues/8

**Comment by jimymodi** [comment]
Also I wan't able to run test. Tried `$ php ../vendor/bin/codecept run`. But couldn't make it run 
```
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

Acceptance Tests (0) --------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------

Functional Tests (0) --------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------

Unit Tests (0) --------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------


Time: 173 ms, Memory: 11.25MB

No tests executed!

```
A guide to run test will help.

**Comment by CSharpRU** [comment]
Strange, because I can run it locally without any problem with `./vendor/bin/codecept run`. Could you provide you PHP version and environment?

**Comment by CSharpRU** [comment]
Anyway, I've merged your changes into master as 3.3.1 version.

**Pull request merged**
